=== desperadotheory/desperadomoney/contract.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Client_id5131 (Client) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="contract" type="contractType">
		<xs:annotation>
			<xs:documentation>
INTERNET-DRAFT: Ko Fujimura XML Voucher: Generic Voucher Language
http://tools.ietf.org/html/draft-ietf-trade-voucher-lang-07
Modified according: The Ricardian Financial Instrument Contract
http://www.systemics.com/docs/ricardo/issuer/contract.html
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="contractType">
		<xs:sequence>
			<xs:element name="Title" type="xs:string"/>
			<xs:element name="contractURL" type="xs:string" minOccurs="0"/>
			<xs:element name="Total" type="xs:decimal">
				<xs:annotation>
					<xs:documentation>Total value of the emmission</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Currency">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="currencyName" type="xs:string"/>
						<xs:element name="currencyLongName" type="xs:string" minOccurs="0"/>
						<xs:element name="currencyLogo" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ValidPeriod" type="ValidPeriodType"/>
			<xs:element name="contractEan13Number" type="xs:string" minOccurs="0"/>
			<xs:element name="Definitions" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The section [definitions] includes terms and definitions that generally desire to be defined in a contract. Following normal procedure in english common law contracts, this section goes up front.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Conditions" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Insula" type="RoleType" minOccurs="0"/>
			<xs:element name="legalIssuer" type="shareType"/>
			<xs:element name="Collector" type="RoleType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Merchandise" type="MerchandiseType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vtsProvider" type="vtsProviderType" minOccurs="0"/>
			<xs:element name="techIssuer" type="RoleType" minOccurs="0"/>
			<xs:element name="key" type="KeyType" default="
			- -----BEGIN CERTIFICATE-----
			- -----END CERTIFICATE-----
			" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RoleType" mixed="true">
		<xs:sequence>
			<xs:element name="name" type="xs:string" default="Name"/>
			<xs:element name="long_name" type="xs:string" default="Long Name" minOccurs="0"/>
			<xs:element name="address" type="xs:string" default="Address" minOccurs="0"/>
			<xs:element name="country" type="xs:string" default="ISOaaNUTSxxx" minOccurs="0"/>
			<xs:element name="email" type="xs:string" default="name@email.com" minOccurs="0"/>
			<xs:element name="url" type="xs:string" default="http://myweb.com" minOccurs="0"/>
			<xs:element name="logo" type="xs:string" default="http://mylogo.com" minOccurs="0"/>
			<xs:element name="citizensID" type="xs:string" default="IDN-XXXXXXX-Y" minOccurs="0"/>
			<xs:element name="BitCoinAddress" type="BitCoinAddressType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="kind"/>
	</xs:complexType>
	<xs:complexType name="ValueType">
		<xs:annotation>
			<xs:documentation>
 The [Ratio] element does not contain any contents.

 The [Ratio] element has a "percentage" attribute that is used to specify the discount ratio of the price of the corresponding merchandize in percentage.			
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="percent" type="xs:decimal"/>
			<xs:element name="resultingFixed" type="xs:decimal" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MerchandiseType" mixed="true">
		<xs:annotation>
			<xs:documentation>
The [Merchandise] element may contain any elements used to specify or restrict the goods or services rendered when the voucher is redeemed.
The sub-elements contained in this element are depending on the application of the voucher and are left to the other domain-specific specifications. Domain-specific elements can be extended as sub-elements using [XML-ns]. 
This element is intended to be interpreted by a collecting system. 
 An implementation of a wallet system does not have to use this element. Any restrictions applied should also be described in the [Description] element or the [Conditions] elements in natural language form to enable users to check the restrictions.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="included" type="xs:boolean" default="true"/>
				<xs:attribute name="pictureURL" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ValidPeriodType">
		<xs:sequence>
			<xs:element name="start" type="xs:dateTime"/>
			<xs:element name="end" type="xs:dateTime"/>
			<xs:element name="issueDate" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KeyType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="vtsProviderType">
		<xs:sequence>
			<xs:element name="provider" type="RoleType"/>
			<xs:element name="vtsVersion" type="xs:string"/>
			<xs:element name="vtsProcessType" default="monetary">
				<xs:annotation>
					<xs:documentation>The following identifiers are defined for the ProcessType

Exchange: Items specified in the [Merchandise] element can be claimed in exchange for the voucher. If this type is selected, neither [Ratio] nor [Fixed] element MUST be specified. Note that this value process type has the same meaning as:
     [Value type="discount"][Ratio percentage="100"/][/Value]

Discount: Items specified in the [Merchandise] element can be purchased at the discount price calculated by the [Ratio] or
     [Fixed] element.

Monetary: Items specified in the [Merchandise] element can be purchased using the value of the voucher. (Note: if the [Merchandise] element is not specified, the voucher can be used for any purchase.) If this type is selected, the [Fixed] element MUST be specified.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="exchange"/>
						<xs:enumeration value="discount"/>
						<xs:enumeration value="monetary"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="shareType">
		<xs:sequence>
			<xs:element name="number" type="xs:string"/>
			<xs:element name="holder" type="RoleType"/>
			<xs:element name="share" type="ValueType"/>
			<xs:element name="participation" type="shareType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BitCoinAddressType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="privateKey"/>
				<xs:attribute name="QR" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== desperadotheory/desperadomoney/PIMECO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 (http://www.altova.com)-->
<?xml-stylesheet type="text/xsl" href="contract.xsl"?>
<contract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contract.xsd">
	<Title>PMC</Title>
	<contractURL>PMCContract.html</contractURL>
	<Total>100000</Total>
	<Currency>
		<currencyName>PMC</currencyName>
		<currencyLongName>PIMECO Community Currency issue and participations </currencyLongName>
		<currencyLogo>images/pmc.jpg</currencyLogo>
	</Currency>
	<ValidPeriod>
		<start>2012-02-21T00:00:00</start>
		<end>2013-02-21T00:00:00</end>
		<issueDate>2012-01-01</issueDate>
	</ValidPeriod>
	<contractEan13Number>536005160012</contractEan13Number>
	<Definitions name="circunscription">INSULA is the DESPERADOS association in the COUNTRY</Definitions>
	<Definitions name="representation">The LEGAL ISSUER represents the COLLECTORS at the INSULA</Definitions>
	<Definitions name="affiliation">COLLECTORS are affiliated companies to the LEGAL ISSUER</Definitions>
	<Definitions name="authorization">LEGAL ISSUER is the authorised institution by the INSULA to issue money in the denominations indicated in CURRENCY</Definitions>
	<Definitions name="holder">HOLDER of this voucher is any Citizen, identified by the INSULA REGISTRATION ID, in possession of money of CURRENCY in paper of electronic format</Definitions>
	<Conditions name="amounts">LEGAL ISSUER will issue money in CURRENCY for a total amount at equivalent of all the MERCHANDISES to be available for trade with CURRENCY during the VALID PERIOD</Conditions>
	<Conditions name="prices">COLLECTORS will indicate the prices of the MERCHANDISES included in this contract in CURRENCY on top of legal tender prices</Conditions>
	<Conditions name="price guarantee">COLLECTORS will not chage the prices in CURRENCY from the date of the issue, until the end of the valid period</Conditions>
	<Conditions name="redemption">COLLECTORS commit to redeem the money in CURRENCY of any INSULA HOLDER for MERCHANDISES worth the price in CURRENCY</Conditions>
	<Conditions name="optional redemption">Optionally, COLLECTORS may redeem CURRENCY of non INSULA HOLDERS the same way</Conditions>
	<Insula>
		<name>DRY-M</name>
		<long_name>Democracia Real Ya Mallorca</long_name>
		<address>na</address>
		<country>ES53</country>
		<email>mallorca@democraciarealya.es</email>
		<url>http://mallorca.democraciarealya.es/</url>
		<logo>images/dry.jpg</logo>
		<citizensID>ES530000000</citizensID>
		<BitCoinAddress QR="" privateKey="text">1LexGaCh4oYcZvMZKAWDTRbG4G4fcnCQCS</BitCoinAddress>
	</Insula>
	<legalIssuer>
		<number>ES53PMCY2012</number>
		<holder kind="account">
			<name>PIMECO</name>
			<long_name>Associaci√≥ del Petit i Mitja Comerc de Mallorca</long_name>
			<address>C/Patronato Obrero, 14 B bajos, 07006 Palma</address>
			<country>ES53</country>
			<email>pimeco@pimeco.com</email>
			<url>http://www.pimeco.com/inicio/</url>
			<logo>images/pimeco.jpg</logo>
			<citizensID>ES530005631</citizensID>
			<BitCoinAddress QR="" privateKey="text">19KTQ8we2N6jrm7x3umpdeVmPWrQ4ibHLf</BitCoinAddress>
		</holder>
		<share>
			<percent>100</percent>
			<resultingFixed>100000</resultingFixed>
		</share>
		<participation>
			<number>ES53PMCY2012ACCN01</number>
			<holder kind="account">
				<name>Jesus ANTOLIN</name>
				<country>ES53</country>
				<citizensID>ES530005000</citizensID>
				<BitCoinAddress>1LRu7zAuCymJMxLe7W6fTVtJY9y9aLjq9w</BitCoinAddress>
			</holder>
			<share>
				<percent>0.66784</percent>
				<resultingFixed>667.84</resultingFixed>
			</share>
					<participation>
			<number>ES53PMCY2012ACCN01S1</number>
			<holder kind="account">
				<name>Jesus ANTOLIN</name>
				<country>ES53</country>
				<citizensID>ES530005000</citizensID>
				<BitCoinAddress>1LRu7zAuCymJMxLe7W6fTVtJY9y9aLjq9w</BitCoinAddress>
			</holder>
			<share>
				<percent>80</percent>
				<resultingFixed>534.272</resultingFixed>
			</share>
			</participation>
			<participation>
				<number>ES53PMCY2012ACCN01S2</number>
				<holder kind="account">
					<name>Jose Maria ARCA</name>
					<country>ES53</country>
					<citizensID>ES530005001</citizensID>
					<BitCoinAddress>1KzcqsmqcBXGoWzAJY4MXHAYc3MozUKaUa</BitCoinAddress>
				</holder>
				<share>
					<percent>10</percent>
					<resultingFixed>66.784</resultingFixed>
				</share>
			</participation>
			<participation>
				<number>ES53PMCY2012ACCN01S3</number>
				<holder kind="account">
					<name>Catalina ARELLANO</name>
					<country>ES53</country>
					<citizensID>ES530005002</citizensID>
					<BitCoinAddress>1EicQKF7vrF5HRHiqhJYybW3QfG9pUSgBT</BitCoinAddress>
				</holder>
				<share>
					<percent>10</percent>
					<resultingFixed>66.784</resultingFixed>
				</share>
							<participation>
				<number>ES53PMCY2012ACCN01S31</number>
				<holder kind="account">
					<name>Catalina ARELLANO</name>
					<country>ES53</country>
					<citizensID>ES530005002</citizensID>
					<BitCoinAddress>1EicQKF7vrF5HRHiqhJYybW3QfG9pUSgBT</BitCoinAddress>
				</holder>
				<share>
					<percent>90</percent>
					<resultingFixed>60.1056</resultingFixed>
				</share>
				</participation>
				<participation>
			<number>ES53PMCY2012ACCN01S32</number>
			<holder kind="account">
				<name>Amayra ARGILES</name>
				<country>ES53</country>
				<citizensID>ES530005003</citizensID>
				<BitCoinAddress>12HmKDtLXDZiYE59hbQZFk65JxoJdoqWaC</BitCoinAddress>
			</holder>
			<share>
				<percent>10</percent>
				<resultingFixed>6.6784</resultingFixed>
			</share>
		</participation>
			</participation>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN02</number>
			<holder kind="account">
				<name>Jose Maria ARCA</name>
				<country>ES53</country>
				<citizensID>ES530005001</citizensID>
				<BitCoinAddress>1KzcqsmqcBXGoWzAJY4MXHAYc3MozUKaUa</BitCoinAddress>
			</holder>
			<share>
				<percent>0.3389</percent>
				<resultingFixed>338.9</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN03</number>
			<holder kind="account">
				<name>Catalina ARELLANO</name>
				<country>ES53</country>
				<citizensID>ES530005002</citizensID>
				<BitCoinAddress>1EicQKF7vrF5HRHiqhJYybW3QfG9pUSgBT</BitCoinAddress>
			</holder>
			<share>
				<percent>0.69969</percent>
				<resultingFixed>699.69</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN04</number>
			<holder kind="account">
				<name>Amayra ARGILES</name>
				<country>ES53</country>
				<citizensID>ES530005003</citizensID>
				<BitCoinAddress>12HmKDtLXDZiYE59hbQZFk65JxoJdoqWaC</BitCoinAddress>
			</holder>
			<share>
				<percent>0.5019</percent>
				<resultingFixed>501.9</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN05</number>
			<holder kind="account">
				<name>Javier ARRAYAS</name>
				<country>ES53</country>
				<citizensID>ES530005004</citizensID>
				<BitCoinAddress>15FDmrjyC1ueWs8rpyKHGTRdsi5CuCZr2o</BitCoinAddress>
			</holder>
			<share>
				<percent>0.08689</percent>
				<resultingFixed>86.89</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN06</number>
			<holder kind="account">
				<name>Enrique ARRIBAS</name>
				<country>ES53</country>
				<citizensID>ES530005005</citizensID>
				<BitCoinAddress>1NihXuUVFMizSNRfwcfVnVsRVvbaW5nzQU</BitCoinAddress>
			</holder>
			<share>
				<percent>0.02133</percent>
				<resultingFixed>21.33</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN07</number>
			<holder kind="account">
				<name>Carballas AVILA</name>
				<country>ES53</country>
				<citizensID>ES530005006</citizensID>
				<BitCoinAddress>1CFMiB87p4g1qdHxhkuH1JTkeL2Rdxtk6B</BitCoinAddress>
			</holder>
			<share>
				<percent>0.34315</percent>
				<resultingFixed>343.15</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN08</number>
			<holder kind="account">
				<name>Matias AYALA</name>
				<country>ES53</country>
				<citizensID>ES530005007</citizensID>
				<BitCoinAddress>1A5Das6axLmV6tFZ3WELogEqZrEwjJ4pJC</BitCoinAddress>
			</holder>
			<share>
				<percent>0.48316</percent>
				<resultingFixed>483.16</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN09</number>
			<holder kind="account">
				<name>Fidel AZPIROZ</name>
				<country>ES53</country>
				<citizensID>ES530005008</citizensID>
				<BitCoinAddress>19DEcLLi4PNvb7dvsSGRYwWoJNGXe5hmBj</BitCoinAddress>
			</holder>
			<share>
				<percent>0.7665</percent>
				<resultingFixed>766.5</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN10</number>
			<holder kind="account">
				<name>Jose Joaquin BALANA</name>
				<country>ES53</country>
				<citizensID>ES530005009</citizensID>
				<BitCoinAddress>1NU4Tyn1ffk58X37fXaN4qsWJ4yqFfSkCD</BitCoinAddress>
			</holder>
			<share>
				<percent>0.39236</percent>
				<resultingFixed>392.36</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN11</number>
			<holder kind="account">
				<name>Francisco Jose BASTIDA</name>
				<country>ES53</country>
				<citizensID>ES530005010</citizensID>
				<BitCoinAddress>1BRDnJEaTPRGGsMKcM6e7ynVTUFvuTqktD</BitCoinAddress>
			</holder>
			<share>
				<percent>0.52546</percent>
				<resultingFixed>525.46</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN12</number>
			<holder kind="account">
				<name>Ramon BELLOQUE</name>
				<country>ES53</country>
				<citizensID>ES530005011</citizensID>
				<BitCoinAddress>1DGsKNbCciPiaouJcfyfd5RRZyv7JysrPT</BitCoinAddress>
			</holder>
			<share>
				<percent>0.75604</percent>
				<resultingFixed>756.04</resultingFixed>
			</share>
		</participation>
		<participation>
			<number>ES53PMCY2012ACCN13</number>
			<holder kind="account">
